<a href="https://colab.research.google.com/github/Amir-Ali-Peymani/DL-practice/blob/main/00_pytroch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00 Pytorch Fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch

In [ ]:
print(torch.__version__)

2.3.1+cu121


In [ ]:
vector = torch.tensor([[7,8],[3,2]])

In [ ]:
print(vector.ndim)

2


In [ ]:
print(vector.shape)

torch.Size([2, 2])


In [ ]:
Matric_3d = torch.tensor([[[1,2,4],
                           [3,2,1],
                           [2,3,5],
                           [2,3,3]]])
Matric_3d

tensor([[[1, 2, 4],
         [3, 2, 1],
         [2, 3, 5],
         [2, 3, 3]]])

In [ ]:
print(Matric_3d.ndim)

3


In [ ]:
print(Matric_3d.shape)

torch.Size([1, 4, 3])


In [ ]:
Matric_3d[0]

tensor([[1, 2, 4],
        [3, 2, 1],
        [2, 3, 5]])

In [ ]:
Matric_3d[0][2]

tensor([2, 3, 5])

In [ ]:
Matric_3d[0][0][2]

tensor(4)

In [ ]:
print("hello there!!")

hello there!!


RANDOM TENSORS

In [ ]:
random_tensor = torch.rand(3,3,3)

In [ ]:
random_tensor

tensor([[[0.8026, 0.9862, 0.8417],
         [0.9953, 0.2018, 0.0745],
         [0.6119, 0.2969, 0.1731]],

        [[0.3929, 0.8860, 0.6352],
         [0.0016, 0.9241, 0.1622],
         [0.9899, 0.5982, 0.4408]],

        [[0.9205, 0.5314, 0.4685],
         [0.2878, 0.4153, 0.2703],
         [0.0998, 0.0904, 0.0756]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([3, 3, 3])

In [ ]:
a = torch.rand(size=(3,4))
a

tensor([[0.1410, 0.0341, 0.9549, 0.5745],
        [0.6216, 0.7300, 0.8913, 0.9727],
        [0.1888, 0.6018, 0.0036, 0.8143]])

In [ ]:
b = torch.rand(size=(3,4))
b

tensor([[0.3389, 0.2451, 0.8248, 0.8687],
        [0.5372, 0.7097, 0.7780, 0.8151],
        [0.9488, 0.3921, 0.9023, 0.4215]])

In [ ]:
c = a*b
c

tensor([[0.4117, 0.1505, 0.0147, 0.0435],
        [0.2936, 0.1652, 0.2691, 0.0990],
        [0.0479, 0.1160, 0.0029, 0.1621]])

In [ ]:
torch_range = torch.range(0,2)
torch_range

<ipython-input-52-1b8dd395ff4e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch_range = torch.range(0,2)


tensor([0., 1., 2.])

In [ ]:
numbers = torch.range(start=1, end=10, step=1)
numbers

<ipython-input-54-56f626e8f6f4>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  numbers = torch.range(start=1, end=10, step=1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
ten_zeros = torch.zeros_like(input=numbers)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
numbers = torch.rand(size=(2,2))
numbers

tensor([[0.6920, 0.6575],
        [0.7767, 0.7257]])

In [4]:
numbers.device

device(type='cpu')

In [5]:
numbers+100

tensor([[100.6920, 100.6575],
        [100.7766, 100.7257]])

In [6]:
numbers*3

tensor([[2.0759, 1.9726],
        [2.3300, 2.1771]])

In [7]:
numbers /2

tensor([[0.3460, 0.3288],
        [0.3883, 0.3629]])

In [8]:
numbers - 2

tensor([[-1.3080, -1.3425],
        [-1.2233, -1.2743]])

In [9]:
torch.mul(numbers, 2)

tensor([[1.3840, 1.3150],
        [1.5533, 1.4514]])

In [10]:
torch.add(numbers, 1)

tensor([[1.6920, 1.6575],
        [1.7767, 1.7257]])

In [15]:
matrix_1 = torch.rand(size=(3,4))
matrix_2 = torch.rand(size=(4,3))
torch.matmul(matrix_1, matrix_2)

tensor([[0.6699, 1.3486, 1.2772],
        [0.6293, 0.9322, 0.5019],
        [0.2718, 0.4602, 1.1541]])

In [17]:
torch.mul(matrix_1, 1)

tensor([[0.7433, 0.8744, 0.2693, 0.6972],
        [0.1681, 0.8006, 0.7533, 0.0769],
        [0.5292, 0.0118, 0.1171, 0.8658]])

In [18]:
matrix_1 @ matrix_2

tensor([[0.6699, 1.3486, 1.2772],
        [0.6293, 0.9322, 0.5019],
        [0.2718, 0.4602, 1.1541]])

In [19]:
torch.mm(matrix_1, matrix_2)

tensor([[0.6699, 1.3486, 1.2772],
        [0.6293, 0.9322, 0.5019],
        [0.2718, 0.4602, 1.1541]])

In [20]:
matrix_one = torch.rand(3, 4)
matrix_two = torch.rand(3, 4)

In [22]:
torch.mm(matrix_one, matrix_two.T)

tensor([[1.8999, 1.0066, 0.9852],
        [1.7458, 0.6412, 1.3950],
        [2.1829, 1.3201, 1.3509]])

In [23]:
torch.min(matrix_one)

tensor(0.0007)

In [24]:
torch.max(matrix_one)

tensor(0.9990)

In [ ]:
!nvidia-smi

Thu Aug 15 15:26:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--