<a href="https://colab.research.google.com/github/Amir-Ali-Peymani/DL-practice/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow
import pandas as pd
import numpy as np
from tensorflow import keras

In [34]:
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore  ... HasCrCard IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619  ...         1              1        101348.88       1
1          2    15647311      Hill          608  ...         0              1        112542.58       0
2          3    15619304      Onio          502  ...         1              0        113931.57       1
3          4    15701354      Boni          699  ...         0              0         93826.63       0
4          5    15737888  Mitchell          850  ...         1              1         79084.10       0

[5 rows x 14 columns]

In [69]:
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
x[0:3]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57]],
      dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder

In [72]:
gender = LabelEncoder()
x[:, 2] = gender.fit_transform(x[:, 2])
x[0:3]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57]],
      dtype=object)

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [74]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))

In [75]:
x[0:2]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58]],
      dtype=object)

In [126]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(6, activation="relu"))
model.add(keras.layers.Dense(6, activation="relu"))
model.add(keras.layers.Dense(1, activation="sigmoid"))

In [127]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
from sklearn.model_selection import train_test_split

In [78]:
x[2]

array([1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
      dtype=object)

In [55]:
train_x, test_x, train_y, test_y = train_test_split(x, y , test_size=0.2, random_state=1)

In [117]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(train_x)
X_test = sc.transform(test_x)

In [118]:
test_x[2]

array([1.000000e+00, 0.000000e+00, 0.000000e+00, 5.310000e+02,
       0.000000e+00, 4.200000e+01, 2.000000e+00, 0.000000e+00,
       2.000000e+00, 0.000000e+00, 1.000000e+00, 9.053747e+04])

In [128]:
model.fit(x=train_x, y=train_y , epochs=100, validation_split=0.15)

Epoch 1/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.6205 - loss: 4384.5815 - val_accuracy: 0.7167 - val_loss: 985.1548
Epoch 2/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7309 - loss: 808.3387 - val_accuracy: 0.6858 - val_loss: 299.6382
Epoch 3/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6923 - loss: 262.8609 - val_accuracy: 0.6767 - val_loss: 98.1796
Epoch 4/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6920 - loss: 66.3052 - val_accuracy: 0.7050 - val_loss: 13.0267
Epoch 5/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6946 - loss: 11.6771 - val_accuracy: 0.7333 - val_loss: 3.1509
Epoch 6/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6830 - loss: 4.8363 - val_accuracy: 0.5608 - val_loss: 10.2212
Epoch 7/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6704 - loss: 6.3799 - val_accuracy: 0.6042 - val_loss: 7.8659
Epoch 8/100
213/213 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6930 - loss: 

In [129]:
model.evaluate(test_x, test_y)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7955 - loss: 1.0807


[1.0439057350158691, 0.796999990940094]

In [101]:
test_y[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0])

In [107]:
test_y[11]

1

In [108]:
print(test_x[11])

[1.000000e+00 0.000000e+00 0.000000e+00 6.140000e+02 1.000000e+00
 4.000000e+01 6.000000e+00 0.000000e+00 1.000000e+00 1.000000e+00
 1.000000e+00 2.033979e+04]


In [112]:
sample = test_x[11].reshape(1, -1)
print(sample)

[[1.000000e+00 0.000000e+00 0.000000e+00 6.140000e+02 1.000000e+00
  4.000000e+01 6.000000e+00 0.000000e+00 1.000000e+00 1.000000e+00
  1.000000e+00 2.033979e+04]]


In [113]:
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[0.2085584]], dtype=float32)

In [111]:
result = np.array(test_y[11].reshape(1,-1))
print(result)

[[1]]


In [122]:
y_predict = model.predict(test_x)
y_predict= (y_predict>0.5)
print(np.concatenate((y_predict.reshape(len(y_predict),1), test_y.reshape(len(test_y),1)), 1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_predict, test_y)
print(cm)
accuracy_score(test_y, y_predict)

[[1584  415]
 [   1    0]]


0.792