<a href="https://colab.research.google.com/github/Amir-Ali-Peymani/DL-practice/blob/main/wide_and_deep_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow
from tensorflow import keras
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
houses = fetch_california_housing()

In [25]:
houses

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
x = houses["data"]
y = houses["target"]

In [32]:
x[0:2]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02]])

In [5]:
train_x0 , test_x, train_y0, test_y = train_test_split(x, y , test_size= 0.2 , random_state=1)

In [6]:
train_x1, validation_x, train_y1, validation_y = train_test_split(train_x0, train_y0)

In [13]:
scaler= StandardScaler()
test_x = scaler.fit_transform(test_x)
train_x1 = scaler.fit_transform(train_x1)
validation_x = scaler.fit_transform(validation_x)

In [11]:
train_x1[0:2]

array([[ 0.38014549,  1.05069034, -0.05497043,  0.05785442, -0.26688386,
        -0.70041614, -0.74623598,  0.56430692],
       [ 0.14296278,  0.25594381, -0.39301028, -0.21119519, -0.42888873,
         2.83028703, -0.88698805,  0.8511483 ]])

In [14]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(50, activation="relu"))
model.add(keras.layers.Dense(1))

In [15]:
model.compile(loss= "mean_squared_error",
              optimizer = "sgd",
              metrics = ["mean_absolute_error"])

In [16]:
model.fit(train_x1, train_y1, epochs=60, validation_data=[validation_x, validation_y])

Epoch 1/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 1.2947 - mean_absolute_error: 0.7603 - val_loss: 0.5203 - val_mean_absolute_error: 0.5294
Epoch 2/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5216 - mean_absolute_error: 0.5096 - val_loss: 0.4914 - val_mean_absolute_error: 0.5205
Epoch 3/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4479 - mean_absolute_error: 0.4730 - val_loss: 0.4519 - val_mean_absolute_error: 0.4992
Epoch 4/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4059 - mean_absolute_error: 0.4537 - val_loss: 0.5778 - val_mean_absolute_error: 0.5707
Epoch 5/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4060 - mean_absolute_error: 0.4527 - val_loss: 0.8956 - val_mean_absolute_error: 0.7044
Epoch 6/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3846 - mean_absolute_error: 0.4426 - val_loss: 1.0790 - val_mean_absolute_error: 0.7680
Epoch 7/60
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3746 - mean_absolute_error: 0.4325 - v

In [17]:
model.evaluate(test_x, test_y)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18.9084 - mean_absolute_error: 2.5866


[19.452682495117188, 2.640848398208618]

In [62]:
test_x[1:2]

array([[-1.00593809,  0.66570524, -0.16519684, -0.11154454, -0.25064513,
        -0.04004423,  0.54301993, -0.10941961]])

In [63]:
model.predict(test_x[1:2])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[0.56382865]], dtype=float32)

In [64]:
test_y[1:2]

array([0.707])

In [18]:
input_ = keras.layers.Input(shape=train_x1.shape[1:])
hidden_layer1= keras.layers.Dense(50, activation="relu")(input_)
hidden_layer2 = keras.layers.Dense(25, activation="relu")(hidden_layer1)
concatenate_layer = keras.layers.Concatenate()([input_, hidden_layer2])
output= keras.layers.Dense(1)(concatenate_layer)
model = keras.Model(inputs=[input_], outputs=[output])

In [19]:
model.compile(loss= "mean_squared_error",
              optimizer = "sgd",
              metrics = ["mean_absolute_error"])

In [20]:
model.fit(train_x1, train_y1, epochs=50, validation_data=[validation_x, validation_y])

Epoch 1/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2.8166 - mean_absolute_error: 0.8202 - val_loss: 0.9123 - val_mean_absolute_error: 0.7022
Epoch 2/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.9550 - mean_absolute_error: 0.5319 - val_loss: 0.9767 - val_mean_absolute_error: 0.6794
Epoch 3/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.4839 - mean_absolute_error: 0.4990 - val_loss: 0.5482 - val_mean_absolute_error: 0.5274
Epoch 4/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.4283 - mean_absolute_error: 0.4751 - val_loss: 0.8451 - val_mean_absolute_error: 0.5418
Epoch 5/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4761 - mean_absolute_error: 0.4836 - val_loss: 0.4869 - val_mean_absolute_error: 0.5282
Epoch 6/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4063 - mean_absolute_error: 0.4578 - val_loss: 0.5579 - val_mean_absolute_error: 0.5596
Epoch 7/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4117 - mean_absolute_error: 0.4586 - v

##Split Input to A & B

In [21]:
x_train_s_1 , x_train_s_2 = train_x1[:, :6], train_x1[:, -4:]
x_validation_s_1, x_validation_s_2 =validation_x[:, :6], validation_x[:, -4:]
x_test_s_1, x_test_s_2 = test_x[:, :6], test_x[:, -4:]

In [22]:
x_train_s_1

array([[-0.52837711, -0.92127216, -0.39874584,  0.16755994, -0.47892605,
        -0.04362223],
       [ 0.71779774, -0.28614019,  0.28858143, -0.15253446,  2.21970105,
         0.02534357],
       [ 0.17097191, -1.63579564,  1.15081699,  0.49548549,  1.54883073,
        -0.0125244 ],
       ...,
       [-0.83247843, -0.0479657 , -0.74200041, -0.06963516, -0.34974119,
        -0.05165784],
       [-0.94420626,  1.46047275, -0.34589934, -0.04514481, -0.39072397,
        -0.01506921],
       [-0.7022693 ,  1.38108125, -0.67384838,  0.1417133 , -0.27935772,
        -0.09522915]])

In [23]:
input_1 = keras.layers.Input(shape=[6])
input_2 = keras.layers.Input(shape=[4])
hidden_layer1= keras.layers.Dense(50, activation="relu")(input_1)
hidden_layer2 = keras.layers.Dense(25, activation="relu")(hidden_layer1)
concatenate_layer = keras.layers.Concatenate()([input_2, hidden_layer2])
output= keras.layers.Dense(1)(concatenate_layer)
model = keras.Model(inputs=[input_1, input_2], outputs=[output])

In [24]:
model.compile(loss= "mean_squared_error",
              optimizer = "sgd",
              metrics = ["mean_absolute_error"])

In [25]:
import tensorflow as tf
history = model.fit((x_train_s_1, x_train_s_2), train_y1, epochs=50,
                    validation_data=((x_validation_s_1, x_validation_s_2), validation_y))


Epoch 1/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.5465 - mean_absolute_error: 0.7878 - val_loss: 3.0975 - val_mean_absolute_error: 0.9256
Epoch 2/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 161100.5781 - mean_absolute_error: 11.1191 - val_loss: 4.5902 - val_mean_absolute_error: 0.9530
Epoch 3/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0895 - mean_absolute_error: 0.8103 - val_loss: 0.9998 - val_mean_absolute_error: 0.7695
Epoch 4/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0415 - mean_absolute_error: 0.7860 - val_loss: 0.9493 - val_mean_absolute_error: 0.7509
Epoch 5/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0219 - mean_absolute_error: 0.7781 - val_loss: 0.9741 - val_mean_absolute_error: 0.7682
Epoch 6/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0015 - mean_absolute_error: 0.7699 - val_loss: 0.9624 - val_mean_absolute_error: 0.7580
Epoch 7/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.0202 - mean_absolute_error: 0.78

Two outputs

In [36]:
input_1 = keras.layers.Input(shape=[6])
input_2 = keras.layers.Input(shape=[4])
hidden_layer1= keras.layers.Dense(50, activation="relu")(input_1)
hidden_layer2 = keras.layers.Dense(25, activation="relu")(hidden_layer1)
concatenate_layer = keras.layers.Concatenate()([input_2, hidden_layer2])
output = keras.layers.Dense(1)(concatenate_layer)
helper_output = keras.layers.Dense(1, name="helper_output")(hidden_layer2)
model = keras.Model(inputs=[input_1, input_2], outputs=[output, helper_output])

In [37]:
model.compile(
    loss=["mse", "mse"],
    loss_weights=[0.8, 0.2],
    optimizer="sgd",
    metrics=[["mean_absolute_error"], ["mean_absolute_error"]]
)

In [38]:
history = model.fit(
    (x_train_s_1, x_train_s_2),
    (train_y1, train_y1),
    epochs=50,
    validation_data=(
        (x_validation_s_1, x_validation_s_2),
        (validation_y, validation_y)
    )
)

Epoch 1/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - dense_20_mean_absolute_error: 0.8588 - helper_output_mean_absolute_error: 0.9441 - loss: 1.5596 - val_dense_20_mean_absolute_error: 0.5456 - val_helper_output_mean_absolute_error: 0.5901 - val_loss: 0.6654
Epoch 2/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - dense_20_mean_absolute_error: 0.5706 - helper_output_mean_absolute_error: 0.5797 - loss: 1.7371 - val_dense_20_mean_absolute_error: 0.5325 - val_helper_output_mean_absolute_error: 0.5568 - val_loss: 0.7015
Epoch 3/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - dense_20_mean_absolute_error: 0.5492 - helper_output_mean_absolute_error: 0.5440 - loss: 1.7695 - val_dense_20_mean_absolute_error: 0.4942 - val_helper_output_mean_absolute_error: 0.5340 - val_loss: 0.5275
Epoch 4/50
387/387 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - dense_20_mean_absolute_error: 0.4873 - helper_output_mean_absolute_error: 0.5301 - loss: 0.5445 - val_dense_20_mean_absolute_error: 0.4796 - val_helper_output_mean_ab